on:
  push:
    branches:
      - main


jobs:
  deploy-to-connect:
    runs-on: macOS-latest
    env:
      APP_NAME: "shiny_pdb"
      SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
      SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@master
        with:
          r-version: '4.1.1'

      - name: Install renv
        run: |
          install.packages("renv")
        shell: Rscript {0}

      - name: Restore environment
        run: |
          renv::consent(TRUE)
          renv::restore()
        shell: Rscript {0}


      - name: Deploy to RStudio Connect
        run: |
          rsconnect::setAccountInfo(name   = 'sam-levin',
                                    token  = ${{secrets.SHINYAPPS_TOKEN}},
                                    secret = ${{secrets.SHINYAPPS_SECRET}})
          rsconnect::deployApp(appName = 'shiny_pdb',
                               appFiles = c('app.R',
                                            'www/map.md',
                                            'www/home.md',
                                            'www/mods.md'),
                               logLevel = 'verbose')
        shell: Rscript {0}
